# Generated by Django 6.1 on 2026-09-01 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('gender', models.CharField(choices=[('MEN', 'Men'), ('WOMEN', 'Women'), ('UNISEX', 'Unisex')], default='UNISEX', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('size', models.CharField(default='100ml', max_length=50)),
                ('concentration', models.CharField(choices=[('EDP', 'Eau de Parfum'), ('EDT', 'Eau de Toilette'), ('EDC', 'Eau de Cologne'), ('PARFUM', 'Parfum'), ('OIL', 'Perfume Oil')], default='EDP', max_length=20)),
                ('fragrance_family', models.CharField(blank=True, max_length=100)),
                ('top_notes', models.TextField(blank=True, help_text='Example: Bergamot, Lemon, Apple')),
                ('middle_notes', models.TextField(blank=True, help_text='Example: Lavender, Rose, Jasmine')),
                ('base_notes', models.TextField(blank=True, help_text='Example: Vanilla, Musk, Cedarwood')),
                ('image', models.ImageField(blank=True, null=True, upload_to='perfumes/')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('is_new', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfumes', to='api.category')),
            ],
            options={
                'verbose_name': 'Perfume',
                'verbose_name_plural': 'Perfumes',
                'ordering': ['-created_at'],
            },
        ),
    ]
