# Generated by Django 6.1 on 2026-09-01 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='perfume',
            options={'ordering': ['-created_at']},
        ),
    ]
